ci: build msi (#85)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -13,9 +13,12 @@ jobs:
     runs-on: ubuntu-22.04
     outputs:
       is_stable_version: ${{ steps.parse.outputs.is_stable_version }}
+      version: ${{ steps.parse.outputs.version }}
     steps:
       - id: parse
-        run: echo "is_stable_version=$([[ $GITHUB_REF =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo true || echo false)" >> $GITHUB_OUTPUT
+        run: |
+          echo "is_stable_version=$([[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo true || echo false)" >> $GITHUB_OUTPUT
+          echo "version=${GITHUB_REF_NAME:1}" >> $GITHUB_OUTPUT
 
   pypi:
     needs: validate
@@ -133,7 +136,8 @@ jobs:
           if-no-files-found: error
 
   windows:
-    needs: validate
+    needs: [parse_tag, validate]
+    if: needs.parse_tag.outputs.is_stable_version == 'true'
     runs-on: windows-2022
     steps:
       - uses: actions/checkout@v3
@@ -147,23 +151,30 @@ jobs:
           poetry install
           poetry run pip install pyinstaller==5.13.2
       - run: make build-windows
-      - name: Install InnoSetup
-        run: |
-          Invoke-WebRequest -URI https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe -OutFile is.exe
-          ./is.exe /VERYSILENT
+      - name: Install Advinst
+        uses: caphyon/advinst-github-action@main
+        with:
+          advinst-version: '21.1'
+          advinst-enable-automation: 'true'
       - run: |
-          & "C:/Program Files (x86)/Inno Setup 6/ISCC.exe" ./release-utils/windows/build-installer.iss
-          mv release-utils/windows/Output/rclip.exe release-utils/windows/Output/rclip-${{ github.ref_name }}-installer.exe
+          & ./release-utils/windows/build-msi.ps1 "${{ needs.parse_tag.outputs.version }}"
+          mv build-msi/rclip-SetupFiles/rclip.msi build-msi/rclip-SetupFiles/rclip-${{ needs.parse_tag.outputs.version }}.msi
       - uses: actions/upload-artifact@v3
         with:
           name: windows
-          path: release-utils/windows/Output/rclip-*.exe
+          path: build-msi/rclip-SetupFiles/rclip-*.msi
           if-no-files-found: error
 
   create_release:
     needs: [pypi, snap, appimage, windows, parse_tag]
+    # the windows job doesn't run for pre-releases, but we need to create a release for pre-releases too
+    if: ${{ !cancelled() }}
     runs-on: ubuntu-22.04
     steps:
+      # if any of the needs jobs fail, we don't want to create a release
+      # this is needed because of `if: ${{ !cancelled() }}` above
+      - if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
@@ -178,7 +189,7 @@ jobs:
         uses: ncipollo/release-action@v1
         with:
           name: ${{ github.ref_name }}
-          artifacts: artifacts/pypi/rclip-*,artifacts/snap/rclip_*.snap,artifacts/appimage/rclip-*.AppImage,artifacts/windows/rclip-*.exe
+          artifacts: artifacts/pypi/rclip-*,artifacts/snap/rclip_*.snap,artifacts/appimage/rclip-*.AppImage,artifacts/windows/rclip-*.msi
           bodyFile: release_changelog.txt
           prerelease: ${{ needs.parse_tag.outputs.is_stable_version == 'false' }}
           token: ${{ secrets.GITHUB_TOKEN }}
