build windows MSI for a prerelease in CI, but disable publishing

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -208,7 +208,7 @@ jobs:
 
   windows-build:
     needs: [lint, parse_tag]
-    if: needs.parse_tag.outputs.is_stable_version == 'true'
+    # if: needs.parse_tag.outputs.is_stable_version == 'true'
     runs-on: windows-2022
     steps:
       - uses: actions/checkout@v6
@@ -228,8 +228,10 @@ jobs:
           advinst-version: '23.5'
           advinst-enable-automation: 'true'
       - run: |
-          & ./release-utils/windows/build-msi.ps1 "${{ needs.parse_tag.outputs.version }}"
-          mv build-msi/rclip-SetupFiles/rclip.msi build-msi/rclip-SetupFiles/rclip-${{ needs.parse_tag.outputs.version }}.msi
+          # & ./release-utils/windows/build-msi.ps1 "${{ needs.parse_tag.outputs.version }}"
+          # mv build-msi/rclip-SetupFiles/rclip.msi build-msi/rclip-SetupFiles/rclip-${{ needs.parse_tag.outputs.version }}.msi
+          & ./release-utils/windows/build-msi.ps1 "0.0.1"
+          mv build-msi/rclip-SetupFiles/rclip.msi build-msi/rclip-SetupFiles/rclip-0.0.1-test.msi
       - name: Sign MSI
         run: |
           mkdir signed
@@ -256,32 +258,32 @@ jobs:
         run: Start-Process msiexec.exe -Wait -ArgumentList '/i rclip-${{ needs.parse_tag.outputs.version }}.msi /quiet'
       - uses: ./.github/actions/test-system-rclip
 
-  create_release:
-    needs: [parse_tag, pypi-release, snap-release, appimage-test, windows-test]
-    # the windows job doesn't run for pre-releases, but we need to create a release for pre-releases too
-    if: ${{ !cancelled() }}
-    runs-on: ubuntu-22.04
-    steps:
-      # if any of the needs jobs fail, we don't want to create a release
-      # this is needed because of `if: ${{ !cancelled() }}` above
-      - if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
-      - uses: actions/checkout@v6
-      - uses: actions/download-artifact@v8
-        with:
-          path: artifacts/
-      - name: Rename snaps for GitHub releases page
-        run: |
-          for snap in artifacts/snap-*/*.snap; do
-            mv "$snap" "${snap//_/-}"
-          done
-      - name: Rename AppImage for GitHub releases page
-        run: mv artifacts/appimage/rclip-${{ needs.parse_tag.outputs.version }}-x86_64.AppImage artifacts/appimage/rclip-${{ needs.parse_tag.outputs.version }}-amd64.AppImage
-      - name: Create Release
-        uses: ncipollo/release-action@v1
-        with:
-          name: ${{ github.ref_name }}
-          artifacts: artifacts/pypi/rclip-*,artifacts/snap-amd64/rclip-*.snap,artifacts/snap-arm64/rclip-*.snap,artifacts/appimage/rclip-*.AppImage,artifacts/windows/rclip-*.msi
-          generateReleaseNotes: true
-          prerelease: ${{ needs.parse_tag.outputs.is_stable_version == 'false' }}
-          token: ${{ secrets.GITHUB_TOKEN }}
+  # create_release:
+  #   needs: [parse_tag, pypi-release, snap-release, appimage-test, windows-test]
+  #   # the windows job doesn't run for pre-releases, but we need to create a release for pre-releases too
+  #   if: ${{ !cancelled() }}
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     # if any of the needs jobs fail, we don't want to create a release
+  #     # this is needed because of `if: ${{ !cancelled() }}` above
+  #     - if: ${{ contains(needs.*.result, 'failure') }}
+  #       run: exit 1
+  #     - uses: actions/checkout@v6
+  #     - uses: actions/download-artifact@v8
+  #       with:
+  #         path: artifacts/
+  #     - name: Rename snaps for GitHub releases page
+  #       run: |
+  #         for snap in artifacts/snap-*/*.snap; do
+  #           mv "$snap" "${snap//_/-}"
+  #         done
+  #     - name: Rename AppImage for GitHub releases page
+  #       run: mv artifacts/appimage/rclip-${{ needs.parse_tag.outputs.version }}-x86_64.AppImage artifacts/appimage/rclip-${{ needs.parse_tag.outputs.version }}-amd64.AppImage
+  #     - name: Create Release
+  #       uses: ncipollo/release-action@v1
+  #       with:
+  #         name: ${{ github.ref_name }}
+  #         artifacts: artifacts/pypi/rclip-*,artifacts/snap-amd64/rclip-*.snap,artifacts/snap-arm64/rclip-*.snap,artifacts/appimage/rclip-*.AppImage,artifacts/windows/rclip-*.msi
+  #         generateReleaseNotes: true
+  #         prerelease: ${{ needs.parse_tag.outputs.is_stable_version == 'false' }}
+  #         token: ${{ secrets.GITHUB_TOKEN }}
